Update files to make it multilanguage
stweil/qemu pull request #6
Opened 2019-07-23 09:24 UTC by bovirus

Update NSIS script
Update language fiels

Now the installer seems full translated.

Please test.

I cannot test the icon description because the installer didn't create program group.

Thanks.

2019-08-02 20:15 UTC, stweil requested changes
Thank you for this update. It works basically. Here are some small comments. I also had to add files for German, French and Spanish, because otherwise those languages would not work.

2019-08-02 20:15 UTC, stweil commented on installer/installer_strings_english.nsh
> +;-------------------------------- Installer text strings (English - LangID ${LANG_English}3)
Why does the comment include this: `${LANG_English}3`?

2019-08-02 20:15 UTC, stweil commented on installer/installer_strings_italian.nsh
> +;-------------------------------- Installer text strings (Italian - LangID ${LANG_Italian})
See comment above.

2019-08-02 20:15 UTC, stweil commented on qemu.nsi
> +!addincludedir installer
```suggestion
!addincludedir ${SRCDIR}/installer
```

2019-08-02 20:15 UTC, stweil commented on qemu.nsi
> -;--------------------------------
Why was this code part moved up?

2019-08-02 20:18 UTC, stweil requested changes

2019-08-02 20:18 UTC, stweil commented on installer/installer_strings_english.nsh
> +LangString Visit_QEMU_WIki_Link ${LANG_ENGLISH} "Visit the QEMU Wiki online!"
```suggestion
LangString Visit_QEMU_Wiki_Link ${LANG_ENGLISH} "Visit the QEMU Wiki online!"
```

2019-08-02 20:18 UTC, stweil commented on installer/installer_strings_italian.nsh
> +LangString Visit_QEMU_WIki_Link ${LANG_ITALIAN} "Visita il Wiki QEMU su internet"
```suggestion
LangString Visit_QEMU_Wiki_Link ${LANG_ITALIAN} "Visita il Wiki QEMU su internet"
```

2019-08-02 20:18 UTC, stweil commented on qemu.nsi
> +!define MUI_FINISHPAGE_LINK $(Visit_QEMU_WIki_Link)
```suggestion
!define MUI_FINISHPAGE_LINK $(Visit_QEMU_Wiki_Link)
```

2019-08-02 20:20 UTC, stweil commented
@bovirus, I still need a signed commit from you, otherwise your contribution won't be accepted by upstream QEMU (see https://wiki.qemu.org/Contribute/SubmitAPatch).

2019-08-03 06:44 UTC, bovirus commented
@stweil 

Could be explain em in details how can help you and what I should do?

2019-08-07 10:13 UTC, stweil commented
Your commit must have a commit message which ends with a `Signed-off-by` line like this one:

    Signed-off-by: YOUR_FULL_NAME <EMAIL_NAME@EMAIL_DOMAIN>

(replace the two parts with your full name (first name and family name) and your e-mail address using valid data)

By the way: the latest installers at https://qemu.weilnetz.de/ include your translation. I still need your `Signed-off-by` to integrate your contribution into the official QEMU code.

2019-08-07 10:17 UTC, bovirus commented
Hello.

Thanks for the explanation.

Could you please add them as

Signed-off-by: bovirus <bovirus@gmail.com<mailto:bovirus@gmail.com>>

This my personal (not office) reference

Thanks. KR.


Da: Stefan Weil <notifications@github.com>
Inviato: mercoledì 7 agosto 2019 12:13
A: stweil/qemu <qemu@noreply.github.com>
Cc: Roberto Boriotti <Roberto.Boriotti@canon-europe.com>; Mention <mention@noreply.github.com>
Oggetto: [FROM EXTERNAL] Re: [stweil/qemu] Update files to make it multilanguage (#6)


Your commit must have a commit message which ends with a Signed-off-by line like this one:

Signed-off-by: YOUR_FULL_NAME <EMAIL_NAME@EMAIL_DOMAIN>

(replace the two parts with your full name (first name and family name) and your e-mail address using valid data)

By the way: the latest installers at https://qemu.weilnetz.de/ include your translation. I still need your Signed-off-by to integrate your contribution into the official QEMU code.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/stweil/qemu/pull/6?email_source=notifications&email_token=AAJUHWUJG2C3CAGRIJ2G3ODQDKN3TA5CNFSM4IGCAILKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3X5MBY#issuecomment-519034375>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAJUHWQWV6OMOIUDTSJYSGDQDKN3TANCNFSM4IGCAILA>.

2019-08-07 10:26 UTC, stweil commented
That would not be accepted by the QEMU maintainers. Quote from the contributor guidelines: 

> Please use your real name to sign a patch (not an alias or acronym).

2019-08-07 11:13 UTC, bovirus commented
@stweil 

Thanks again for thed etail.
Please use

Signed-off-by: Roberto Boriotti <bovirus@gmail.com>

2021-09-04 04:28 UTC, stweil commented
Multilanguage was added meanwhile, so I think this pull request can be closed. Please tell me if something is still missing.

2021-09-04 04:28 UTC, closed without merging

2021-09-04 06:41 UTC, bovirus commented
@stweil 
Yes you can close this request because instalelr now is multilanguage.
Thanks.